spring:
  application:
    name: league-legends
  datasource:
    url: jdbc:h2:mem:loldata
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

openai:
  url: https://api.openai.com
  api-key: ${OPENAI_SECRET_API_KEY}

gemini:
  url: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_SECRET_API_KEY}